CREATE TABLE token_family (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT REFERENCES authorized_user(id) ON DELETE CASCADE,
    last_generation BIGINT NOT NULL
);


ALTER TABLE refresh_token
    DROP COLUMN user_id,
    ADD COLUMN generation BIGINT NOT NULL;

ALTER TABLE refresh_token
    RENAME family TO family_id;

ALTER TABLE refresh_token
    ADD FOREIGN KEY (family_id) REFERENCES token_family(id) ON DELETE CASCADE;
